### ISSUE TITLE
Sample app can't login.

### ISSUE THREAD

**Issue by tmshih** [nestlabs/android-sdk-sample#3]
Login nest user and come with exception reports as following:

com.nestlabs.sdk.sample E/NestAuthActivity: Failed to parse response for token.
  com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "user_id" (class com.nestlabs.sdk.NestToken), not marked as ignorable (2 known properties: , "expires_in", "access_token"])

**Comment by harenj** [comment]
@tmshih I believe this issue is resolved. See the most recent posts here: https://github.com/nestlabs/android-sdk/issues/27
